services:
  mongodb:
    image: mongo:latest
    container_name: catalogo-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: catalogo_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - catalogo-network

  mongo-express:
    image: mongo-express:latest
    container_name: catalogo-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - catalogo-network

volumes:
  mongodb_data:

networks:
  catalogo-network:
    driver: bridge